var data = 
[
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 19,
	  "rok_studiów": 1,
	  "kierunek": "dziennikarstwo",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 12,
	  "na_odległość": "nie",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "tak",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "nie",
	  "seks": "nie",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "nie",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 21,
	  "rok_studiów": 2,
	  "kierunek": "psychologia",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "internet",
		 ""
	  ],
	  "ile_trwa": 24,
	  "na_odległość": "tak",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "tak",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "tak",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "nie",
	  "płacenie_randka": "tak",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "m",
	  "wiek": 20,
	  "rok_studiów": 2,
	  "kierunek": "informatyka",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 48,
	  "na_odległość": "nie",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "nie",
	  "warto_szukać": "tak",
	  "nie_monogamia": "tak",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "k",
	  "wiek": 20,
	  "rok_studiów": 2,
	  "kierunek": "informatyka",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "internet",
		 ""
	  ],
	  "ile_trwa": 48,
	  "na_odległość": "nie",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "nie",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "m",
	  "wiek": 26,
	  "rok_studiów": 3,
	  "kierunek": "zarządzanie",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 2,
	  "szukają_długoterm": "nie",
	  "krótkotrwały_zw": "nie",
	  "partner_internet": "tak",
	  "platforma": "inne",
	  "zw_odległość": "nie",
	  "rozstanie": "niedopasowanie seksualne",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "tak",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "partner",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "m",
	  "wiek": 24,
	  "rok_studiów": 4,
	  "kierunek": "informatyka",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 24,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "tak",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "tak",
	  "co_ważniejsze": "partner",
	  "presja_równa_się_krótko": "",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "k",
	  "wiek": 20,
	  "rok_studiów": 2,
	  "kierunek": "informatyka",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 ""
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "nie",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "",
	  "konto_randkowe": "",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "",
	  "sexting": "",
	  "seks": "",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "nie",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "k",
	  "wiek": 21,
	  "rok_studiów": 3,
	  "kierunek": "informatyka",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 1,
	  "szukają_długoterm": "tak",
	  "krótkotrwały_zw": "tak",
	  "partner_internet": "nie",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "tak",
	  "seks_bez_zob": "nie",
	  "partnerka_z_uni": "tak",
	  "konto_randkowe": "tak",
	  "jak_często": "kilka razy tygodniowo",
	  "dzowni_przed": "nie",
	  "dąży_do_spotkania": "nie",
	  "jaki_cel": "partnera",
	  "pandemia": "nie",
	  "co_ważniejsze": "partner",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "m",
	  "wiek": 22,
	  "rok_studiów": 1,
	  "kierunek": "informatyka",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 ""
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "nie",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "tak",
	  "seks_bez_zob": "nie",
	  "partnerka_z_uni": "",
	  "konto_randkowe": "tak",
	  "jak_często": "kilka razy tygodniowo",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "partnera",
	  "pandemia": "",
	  "co_ważniejsze": "partner",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "tak",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "m",
	  "wiek": 22,
	  "rok_studiów": 3,
	  "kierunek": "informatyka",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "internet",
		 ""
	  ],
	  "ile_trwa": 36,
	  "na_odległość": "nie",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "nie",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "m",
	  "wiek": 20,
	  "rok_studiów": 2,
	  "kierunek": "fizyka",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "internet"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 1.5,
	  "szukają_długoterm": "tak",
	  "krótkotrwały_zw": "tak",
	  "partner_internet": "tak",
	  "platforma": "inne",
	  "zw_odległość": "tak",
	  "rozstanie": "odległość",
	  "czy_szukają": "",
	  "seks_bez_zob": "nie",
	  "partnerka_z_uni": "",
	  "konto_randkowe": "",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "nie",
	  "nie_monogamia": "tak",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 20,
	  "rok_studiów": 2,
	  "kierunek": "zarządzanie",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "internet"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 5,
	  "szukają_długoterm": "nie",
	  "krótkotrwały_zw": "nie",
	  "partner_internet": "tak",
	  "platforma": "Tinder, Instagram",
	  "zw_odległość": "nie",
	  "rozstanie": "niekompatybilność",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "nie",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "tak",
	  "jak_często": "codziennie",
	  "dzowni_przed": "nie",
	  "dąży_do_spotkania": "tak",
	  "jaki_cel": "partnera, kolegi",
	  "pandemia": "",
	  "co_ważniejsze": "partner",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 23,
	  "rok_studiów": 2,
	  "kierunek": "psychologia",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 24,
	  "szukają_długoterm": "nie",
	  "krótkotrwały_zw": "tak",
	  "partner_internet": "tak",
	  "platforma": "Tinder",
	  "zw_odległość": "nie",
	  "rozstanie": "niekompatybilność",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "tak",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "tak",
	  "jak_często": "codziennie",
	  "dzowni_przed": "nie",
	  "dąży_do_spotkania": "tak",
	  "jaki_cel": "partnera",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "nie",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "m",
	  "wiek": 21,
	  "rok_studiów": 1,
	  "kierunek": "informatyka",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 0.5,
	  "na_odległość": "nie",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "tak",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "partner",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "nie",
	  "seks": "nie",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "tak",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "k",
	  "wiek": 21,
	  "rok_studiów": 3,
	  "kierunek": "informatyka",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "internet",
		 ""
	  ],
	  "ile_trwa": 30,
	  "na_odległość": "nie",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "tak",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "m",
	  "wiek": 22,
	  "rok_studiów": 3,
	  "kierunek": "informatyka",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 12,
	  "na_odległość": "nie",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "nie",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "m",
	  "wiek": 21,
	  "rok_studiów": 3,
	  "kierunek": "informatyka",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 12,
	  "na_odległość": "nie",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "partner",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "nie",
	  "seks": "nie",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "k",
	  "wiek": 19,
	  "rok_studiów": 1,
	  "kierunek": "ekonomia",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 7,
	  "szukają_długoterm": "nie",
	  "krótkotrwały_zw": "tak",
	  "partner_internet": "tak",
	  "platforma": "Instagram",
	  "zw_odległość": "tak",
	  "rozstanie": "odległość, różnica wartości, niedopasowanie seksualne",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "tak",
	  "partnerka_z_uni": "tak",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "tak",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "m",
	  "wiek": 20,
	  "rok_studiów": 1,
	  "kierunek": "informatyka",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 12,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "nie",
	  "partner_internet": "nie",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "nie",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "nie",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "m",
	  "wiek": 21,
	  "rok_studiów": 3,
	  "kierunek": "informatyka",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "internet"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 18,
	  "szukają_długoterm": "nie",
	  "krótkotrwały_zw": "nie",
	  "partner_internet": "tak",
	  "platforma": "",
	  "zw_odległość": "nie",
	  "rozstanie": "niekompatybilność",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "nie",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "",
	  "co_ważniejsze": "partner",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "tak",
	  "seks": "nie",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "m",
	  "wiek": 21,
	  "rok_studiów": 1,
	  "kierunek": "informatyka",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 60,
	  "szukają_długoterm": "tak",
	  "krótkotrwały_zw": "nie",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "nie",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "m",
	  "wiek": 20,
	  "rok_studiów": 1,
	  "kierunek": "informatyka",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 12,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "nie",
	  "partner_internet": "nie",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "partner",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "nie",
	  "seks": "nie",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "tak",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 21,
	  "rok_studiów": 2,
	  "kierunek": "zarządzanie",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 24,
	  "szukają_długoterm": "nie",
	  "krótkotrwały_zw": "tak",
	  "partner_internet": "nie",
	  "platforma": "",
	  "zw_odległość": "nie",
	  "rozstanie": "niekompatybilność",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "nie",
	  "partnerka_z_uni": "tak",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "tak",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "tak",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "m",
	  "wiek": 22,
	  "rok_studiów": 3,
	  "kierunek": "zarządzanie",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 24,
	  "szukają_długoterm": "nie",
	  "krótkotrwały_zw": "nie",
	  "partner_internet": "nie",
	  "platforma": "",
	  "zw_odległość": "nie",
	  "rozstanie": "niekompatybilność",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "tak",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "tak",
	  "jak_często": "rzadziej",
	  "dzowni_przed": "nie",
	  "dąży_do_spotkania": "nie",
	  "jaki_cel": "partnera, kolegi",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "nie",
	  "płacenie_randka": "tak",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "m",
	  "wiek": 23,
	  "rok_studiów": 3,
	  "kierunek": "informatyka",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 48,
	  "na_odległość": "nie",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "tak",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "tak",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "m",
	  "wiek": 23,
	  "rok_studiów": 3,
	  "kierunek": "informatyka",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 6,
	  "na_odległość": "nie",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "tak",
	  "jak_często": "kilka razy tygodniowo",
	  "dzowni_przed": "tak",
	  "dąży_do_spotkania": "tak",
	  "jaki_cel": "partnera, kolegi, niezobowiązujące",
	  "pandemia": "tak",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "tak",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "m",
	  "wiek": 22,
	  "rok_studiów": 3,
	  "kierunek": "informatyka",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "internet",
		 "internet"
	  ],
	  "ile_trwa": 2,
	  "na_odległość": "nie",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 18,
	  "szukają_długoterm": "nie",
	  "krótkotrwały_zw": "nie",
	  "partner_internet": "tak",
	  "platforma": "Tinder",
	  "zw_odległość": "tak",
	  "rozstanie": "różnica wartości",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "tak",
	  "jak_często": "kilka razy tygodniowo",
	  "dzowni_przed": "tak",
	  "dąży_do_spotkania": "tak",
	  "jaki_cel": "partnera, kolegi, niezobowiązujące",
	  "pandemia": "tak",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "nie",
	  "warto_szukać": "tak",
	  "nie_monogamia": "tak",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "m",
	  "wiek": 18,
	  "rok_studiów": 1,
	  "kierunek": "finanse",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 24,
	  "na_odległość": "nie",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "tak",
	  "konto_randkowe": "tak",
	  "jak_często": "rzadziej",
	  "dzowni_przed": "nie",
	  "dąży_do_spotkania": "nie",
	  "jaki_cel": "",
	  "pandemia": "",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "nie",
	  "warto_szukać": "nie",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "tak",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "k",
	  "wiek": 20,
	  "rok_studiów": 1,
	  "kierunek": "informatyka",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "internet"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 8,
	  "szukają_długoterm": "nie",
	  "krótkotrwały_zw": "nie",
	  "partner_internet": "tak",
	  "platforma": "inne",
	  "zw_odległość": "tak",
	  "rozstanie": "niekompatybilność",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "nie",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "nie",
	  "warto_szukać": "tak",
	  "nie_monogamia": "tak",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe ",
	  "płeć": "m",
	  "wiek": 21,
	  "rok_studiów": 1,
	  "kierunek": "informatyka",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 5,
	  "na_odległość": "tak",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "partner",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "nie",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 19,
	  "rok_studiów": 1,
	  "kierunek": "dziennikarstwo",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 ""
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "nie",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "k",
	  "wiek": 20,
	  "rok_studiów": 1,
	  "kierunek": "informatyka",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 6,
	  "szukają_długoterm": "nie",
	  "krótkotrwały_zw": "nie",
	  "partner_internet": "nie",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "nie",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "nie",
	  "warto_szukać": "nie",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 21,
	  "rok_studiów": 2,
	  "kierunek": "psychologia",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 12,
	  "szukają_długoterm": "tak",
	  "krótkotrwały_zw": "nie",
	  "partner_internet": "tak",
	  "platforma": "inne",
	  "zw_odległość": "nie",
	  "rozstanie": "niekompatybilność",
	  "czy_szukają": "tak",
	  "seks_bez_zob": "nie",
	  "partnerka_z_uni": "tak",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "",
	  "co_ważniejsze": "partner",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "nie",
	  "seks": "nie",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "k",
	  "wiek": 18,
	  "rok_studiów": 1,
	  "kierunek": "finanse",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 1,
	  "szukają_długoterm": "nie",
	  "krótkotrwały_zw": "nie",
	  "partner_internet": "nie",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "nie",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "tak",
	  "jak_często": "rzadziej",
	  "dzowni_przed": "nie",
	  "dąży_do_spotkania": "nie",
	  "jaki_cel": "kolegi",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "nie",
	  "warto_szukać": "nie",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "tak",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 20,
	  "rok_studiów": 1,
	  "kierunek": "psychologia",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 10,
	  "szukają_długoterm": "tak",
	  "krótkotrwały_zw": "nie",
	  "partner_internet": "nie",
	  "platforma": "",
	  "zw_odległość": "nie",
	  "rozstanie": "",
	  "czy_szukają": "tak",
	  "seks_bez_zob": "nie",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "nie",
	  "seks": "nie",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "nie",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 24,
	  "rok_studiów": 5,
	  "kierunek": "psychologia",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 72,
	  "na_odległość": "nie",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "partner",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 22,
	  "rok_studiów": 2,
	  "kierunek": "zarządzanie",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 6,
	  "szukają_długoterm": "nie",
	  "krótkotrwały_zw": "nie",
	  "partner_internet": "tak",
	  "platforma": "Instagram",
	  "zw_odległość": "nie",
	  "rozstanie": "inne",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "tak",
	  "partnerka_z_uni": "tak",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "partner",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "nie",
	  "nie_monogamia": "tak",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "tak",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "m",
	  "wiek": 19,
	  "rok_studiów": 1,
	  "kierunek": "informatyka",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 5,
	  "na_odległość": "tak",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "nie",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "m",
	  "wiek": 20,
	  "rok_studiów": 2,
	  "kierunek": "psychologia",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 ""
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "nie",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "nie",
	  "partnerka_z_uni": "",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 19,
	  "rok_studiów": 1,
	  "kierunek": "psychologia",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 6,
	  "na_odległość": "nie",
	  "czy_byli_kiedyś": "nie",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "tak",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "partner",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "nie",
	  "warto_szukać": "tak",
	  "nie_monogamia": "tak",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 20,
	  "rok_studiów": 1,
	  "kierunek": "psychologia",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 36,
	  "szukają_długoterm": "tak",
	  "krótkotrwały_zw": "tak",
	  "partner_internet": "nie",
	  "platforma": "",
	  "zw_odległość": "nie",
	  "rozstanie": "inne",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "tak",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "tak",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "m",
	  "wiek": 19,
	  "rok_studiów": 1,
	  "kierunek": "zarządzanie",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 12,
	  "szukają_długoterm": "tak",
	  "krótkotrwały_zw": "nie",
	  "partner_internet": "nie",
	  "platforma": "",
	  "zw_odległość": "nie",
	  "rozstanie": "inne",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "nie",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "nie",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 21,
	  "rok_studiów": 2,
	  "kierunek": "psychologia",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 ""
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "nie",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "Tinder",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "tak",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "",
	  "konto_randkowe": "tak",
	  "jak_często": "kilka razy tygodniowo",
	  "dzowni_przed": "nie",
	  "dąży_do_spotkania": "tak",
	  "jaki_cel": "partnera, kolegi",
	  "pandemia": "nie",
	  "co_ważniejsze": "partner",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "nie",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 20,
	  "rok_studiów": 1,
	  "kierunek": "dziennikarstwo",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 3,
	  "szukają_długoterm": "nie",
	  "krótkotrwały_zw": "nie",
	  "partner_internet": "nie",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "nie",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "nie",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 20,
	  "rok_studiów": 1,
	  "kierunek": "dziennikarstwo",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 3,
	  "szukają_długoterm": "nie",
	  "krótkotrwały_zw": "tak",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "niekompatybilność",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "nie",
	  "partnerka_z_uni": "tak",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "partner",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "tak",
	  "seks": "nie",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "nie",
	  "warto_szukać": "nie",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "tak",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 22,
	  "rok_studiów": 3,
	  "kierunek": "psychologia",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "internet",
		 "internet"
	  ],
	  "ile_trwa": 30,
	  "na_odległość": "nie",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 24,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "tak",
	  "partner_internet": "",
	  "platforma": "inne",
	  "zw_odległość": "",
	  "rozstanie": "odległość",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "tak",
	  "co_ważniejsze": "partner",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 19,
	  "rok_studiów": 1,
	  "kierunek": "psychologia",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 6,
	  "na_odległość": "nie",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "tak",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "partner",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "nie",
	  "warto_szukać": "tak",
	  "nie_monogamia": "tak",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "m",
	  "wiek": 22,
	  "rok_studiów": 3,
	  "kierunek": "informatyka",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 48,
	  "na_odległość": "nie",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "m",
	  "wiek": 20,
	  "rok_studiów": 1,
	  "kierunek": "zarządzanie",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "internet",
		 "internet"
	  ],
	  "ile_trwa": 48,
	  "na_odległość": "tak",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "tak",
	  "co_ważniejsze": "partner",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "nie",
	  "nie_monogamia": "tak",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 21,
	  "rok_studiów": 1,
	  "kierunek": "psychologia",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 "na żywo"
	  ],
	  "ile_trwa": 1,
	  "na_odległość": "tak",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 4,
	  "szukają_długoterm": "tak",
	  "krótkotrwały_zw": "nie",
	  "partner_internet": "nie",
	  "platforma": "",
	  "zw_odległość": "tak",
	  "rozstanie": "niekompatybilność",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "tak",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 21,
	  "rok_studiów": 3,
	  "kierunek": "zarządzanie",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 24,
	  "szukają_długoterm": "nie",
	  "krótkotrwały_zw": "tak",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "nie",
	  "rozstanie": "odległość",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "nie",
	  "partnerka_z_uni": "tak",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "tak",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "tak",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "m",
	  "wiek": 22,
	  "rok_studiów": 3,
	  "kierunek": "zarządzanie",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 24,
	  "szukają_długoterm": "nie",
	  "krótkotrwały_zw": "nie",
	  "partner_internet": "nie",
	  "platforma": "",
	  "zw_odległość": "nie",
	  "rozstanie": "",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "tak",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "tak",
	  "jak_często": "rzadziej",
	  "dzowni_przed": "nie",
	  "dąży_do_spotkania": "nie",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "nie",
	  "płacenie_randka": "tak",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "m",
	  "wiek": 23,
	  "rok_studiów": 3,
	  "kierunek": "informatyka",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 60,
	  "na_odległość": "nie",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "tak",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "tak",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "m",
	  "wiek": 23,
	  "rok_studiów": 3,
	  "kierunek": "informatyka",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 1,
	  "na_odległość": "nie",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "tak",
	  "jak_często": "kilka razy tygodniowo",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "partnera, kolegi, niezobowiązujące",
	  "pandemia": "tak",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "tak",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "m",
	  "wiek": 22,
	  "rok_studiów": 3,
	  "kierunek": "informatyka",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "internet",
		 "internet"
	  ],
	  "ile_trwa": 2,
	  "na_odległość": "nie",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 18,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "tak",
	  "platforma": "Tinder",
	  "zw_odległość": "tak",
	  "rozstanie": "różnica wartości",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "tak",
	  "jak_często": "kilka razy tygodniowo",
	  "dzowni_przed": "tak",
	  "dąży_do_spotkania": "tak",
	  "jaki_cel": "partnera, kolegi, niezobowiązujące",
	  "pandemia": "tak",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "nie",
	  "warto_szukać": "tak",
	  "nie_monogamia": "tak",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "m",
	  "wiek": 18,
	  "rok_studiów": 1,
	  "kierunek": "finanse",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 24,
	  "na_odległość": "nie",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "tak",
	  "konto_randkowe": "tak",
	  "jak_często": "rzadziej",
	  "dzowni_przed": "nie",
	  "dąży_do_spotkania": "nie",
	  "jaki_cel": "",
	  "pandemia": "",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "nie",
	  "warto_szukać": "nie",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "tak",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "m",
	  "wiek": 21,
	  "rok_studiów": 1,
	  "kierunek": "informatyka",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 5,
	  "na_odległość": "tak",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "partner",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "nie",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 22,
	  "rok_studiów": 2,
	  "kierunek": "zarządzanie",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 6,
	  "szukają_długoterm": "nie",
	  "krótkotrwały_zw": "nie",
	  "partner_internet": "tak",
	  "platforma": "Instagram",
	  "zw_odległość": "nie",
	  "rozstanie": "inne",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "tak",
	  "partnerka_z_uni": "tak",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "tak",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "m",
	  "wiek": 19,
	  "rok_studiów": 1,
	  "kierunek": "informatyka",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 5,
	  "na_odległość": "tak",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "nie",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 19,
	  "rok_studiów": 1,
	  "kierunek": "dziennikarstwo",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 ""
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "nie",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "nie",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "m",
	  "wiek": 20,
	  "rok_studiów": 1,
	  "kierunek": "informatyka",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 6,
	  "szukają_długoterm": "nie",
	  "krótkotrwały_zw": "nie",
	  "partner_internet": "nie",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "nie",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "nie",
	  "warto_szukać": "nie",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 21,
	  "rok_studiów": 2,
	  "kierunek": "psychologia",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 12,
	  "szukają_długoterm": "tak",
	  "krótkotrwały_zw": "nie",
	  "partner_internet": "tak",
	  "platforma": "inne",
	  "zw_odległość": "nie",
	  "rozstanie": "niekompatybilność",
	  "czy_szukają": "tak",
	  "seks_bez_zob": "nie",
	  "partnerka_z_uni": "tak",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "nie",
	  "seks": "nie",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "k",
	  "wiek": 17,
	  "rok_studiów": 1,
	  "kierunek": "finanse",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 1,
	  "szukają_długoterm": "nie",
	  "krótkotrwały_zw": "nie",
	  "partner_internet": "nie",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "nie",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "tak",
	  "jak_często": "rzadziej",
	  "dzowni_przed": "nie",
	  "dąży_do_spotkania": "nie",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "nie",
	  "warto_szukać": "nie",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "tak",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 20,
	  "rok_studiów": 1,
	  "kierunek": "psychologia",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 10,
	  "szukają_długoterm": "tak",
	  "krótkotrwały_zw": "nie",
	  "partner_internet": "nie",
	  "platforma": "",
	  "zw_odległość": "nie",
	  "rozstanie": "",
	  "czy_szukają": "tak",
	  "seks_bez_zob": "nie",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "nie",
	  "seks": "nie",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "nie",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 19,
	  "rok_studiów": 1,
	  "kierunek": "zarządzanie",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 12,
	  "szukają_długoterm": "tak",
	  "krótkotrwały_zw": "nie",
	  "partner_internet": "nie",
	  "platforma": "",
	  "zw_odległość": "nie",
	  "rozstanie": "",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "nie",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "nie",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 20,
	  "rok_studiów": 1,
	  "kierunek": "zarządzanie",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 2,
	  "szukają_długoterm": "tak",
	  "krótkotrwały_zw": "nie",
	  "partner_internet": "nie",
	  "platforma": "",
	  "zw_odległość": "nie",
	  "rozstanie": "",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "nie",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "tak",
	  "seks": "nie",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "nie",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 19,
	  "rok_studiów": 1,
	  "kierunek": "dziennikarstwo",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 36,
	  "na_odległość": "tak",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 19,
	  "rok_studiów": 1,
	  "kierunek": "dziennikarstwo",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 12,
	  "na_odległość": "nie",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "",
	  "co_ważniejsze": "partner",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "nie",
	  "warto_szukać": "nie",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "k",
	  "wiek": 23,
	  "rok_studiów": 2,
	  "kierunek": "matematyka",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 12,
	  "szukają_długoterm": "tak",
	  "krótkotrwały_zw": "tak",
	  "partner_internet": "nie",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "nie",
	  "partnerka_z_uni": "tak",
	  "konto_randkowe": "tak",
	  "jak_często": "kilka razy dziennie",
	  "dzowni_przed": "nie",
	  "dąży_do_spotkania": "nie",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "nie",
	  "seks": "nie",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 20,
	  "rok_studiów": 1,
	  "kierunek": "dziennikarstwo",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 4,
	  "na_odległość": "nie",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "tak",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "partner",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "tak",
	  "seks": "nie",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "nie",
	  "warto_szukać": "nie",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "m",
	  "wiek": 21,
	  "rok_studiów": 2,
	  "kierunek": "psychologia",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "internet",
		 ""
	  ],
	  "ile_trwa": 36,
	  "na_odległość": "nie",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "tak",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "tak",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "m",
	  "wiek": 20,
	  "rok_studiów": 1,
	  "kierunek": "psychologia",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 36,
	  "szukają_długoterm": "tak",
	  "krótkotrwały_zw": "tak",
	  "partner_internet": "nie",
	  "platforma": "",
	  "zw_odległość": "nie",
	  "rozstanie": "",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "tak",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "tak",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 23,
	  "rok_studiów": 5,
	  "kierunek": "psychologia",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 36,
	  "na_odległość": "tak",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "tak",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 20,
	  "rok_studiów": 2,
	  "kierunek": "psychologia",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 36,
	  "na_odległość": "nie",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "partner",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "",
	  "warto_szukać": "nie",
	  "nie_monogamia": "tak",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "m",
	  "wiek": 20,
	  "rok_studiów": 1,
	  "kierunek": "psychologia",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 6,
	  "na_odległość": "nie",
	  "czy_byli_kiedyś": "nie",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "tak",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nei",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "nie",
	  "seks": "nie",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "nie",
	  "warto_szukać": "nie",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "nie",
	  "płacenie_randka": "",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 21,
	  "rok_studiów": 1,
	  "kierunek": "psychologia",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 18,
	  "szukają_długoterm": "tak",
	  "krótkotrwały_zw": "tak",
	  "partner_internet": "nie",
	  "platforma": "",
	  "zw_odległość": "nie",
	  "rozstanie": "niekompatybilność",
	  "czy_szukają": "tak",
	  "seks_bez_zob": "tak",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak ",
	  "partner_ka_na_stałe": "nie",
	  "płacenie_randka": "",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 21,
	  "rok_studiów": 2,
	  "kierunek": "psychologia",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 15,
	  "na_odległość": "tak",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "nie",
	  "seks": "nie",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 25,
	  "rok_studiów": 5,
	  "kierunek": "psychologia",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "internet",
		 ""
	  ],
	  "ile_trwa": 72,
	  "na_odległość": "nie",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "tak",
	  "jak_często": "rzadziej",
	  "dzowni_przed": "nie",
	  "dąży_do_spotkania": "nie",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "partner",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "nie",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "tak",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "k",
	  "wiek": 20,
	  "rok_studiów": 1,
	  "kierunek": "informatyka",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 ""
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "nie",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "nie",
	  "seks": "nie",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 20,
	  "rok_studiów": 2,
	  "kierunek": "psychologia",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 ""
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "nie",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "nie",
	  "partnerka_z_uni": "",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "m",
	  "wiek": 23,
	  "rok_studiów": 3,
	  "kierunek": "informatyka",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 12,
	  "na_odległość": "nie",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "nie",
	  "warto_szukać": "tak",
	  "nie_monogamia": "tak",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "m",
	  "wiek": 21,
	  "rok_studiów": 2,
	  "kierunek": "informatyka",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 36,
	  "na_odległość": "nie",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "tak",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "tak",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "tak",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "tak",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 21,
	  "rok_studiów": 2,
	  "kierunek": "psychologia",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 24,
	  "na_odległość": "tak",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "tak",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "",
	  "co_ważniejsze": "partner",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "nie",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 21,
	  "rok_studiów": 2,
	  "kierunek": "zarządzanie",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 36,
	  "szukają_długoterm": "nie",
	  "krótkotrwały_zw": "tak",
	  "partner_internet": "nie",
	  "platforma": "",
	  "zw_odległość": "nie",
	  "rozstanie": "różnica wartości",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "nie",
	  "warto_szukać": "nie",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "m",
	  "wiek": 19,
	  "rok_studiów": 1,
	  "kierunek": "zarządzanie",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 12,
	  "na_odległość": "nie",
	  "czy_byli_kiedyś": "",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "tak",
	  "co_ważniejsze": "partner",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "nie",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "m",
	  "wiek": 19,
	  "rok_studiów": 1,
	  "kierunek": "informatyka",
	  "związek_teraz": "tak",
	  "jak_się_poznali": [
		 "na żywo",
		 ""
	  ],
	  "ile_trwa": 36,
	  "na_odległość": "nie",
	  "czy_byli_kiedyś": "nie",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "tak",
	  "jak_często": "rzadziej",
	  "dzowni_przed": "nie",
	  "dąży_do_spotkania": "nie",
	  "jaki_cel": "niezobowiązujące relacje",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "nie",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "tak",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 20,
	  "rok_studiów": 1,
	  "kierunek": "zarządzanie",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "internet"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 18,
	  "szukają_długoterm": "nie",
	  "krótkotrwały_zw": "nie",
	  "partner_internet": "nie",
	  "platforma": "",
	  "zw_odległość": "nie",
	  "rozstanie": "niekompatybilność",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "tak",
	  "partnerka_z_uni": "tak",
	  "konto_randkowe": "nie",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "tak",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "m",
	  "wiek": 23,
	  "rok_studiów": 3,
	  "kierunek": "informatyka",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 ""
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "nie",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "",
	  "konto_randkowe": "",
	  "jak_często": "",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "",
	  "co_ważniejsze": "",
	  "presja_równa_się_krótko": "",
	  "sexting": "",
	  "seks": "",
	  "ta_sama_płeć": "",
	  "kiedyś_łatwiej": "",
	  "warto_szukać": "",
	  "nie_monogamia": "",
	  "małżeństwo": "",
	  "partner_ka_na_stałe": "",
	  "płacenie_randka": "",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "m",
	  "wiek": 22,
	  "rok_studiów": 3,
	  "kierunek": "informatyka",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 ""
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "nie",
	  "ile_trwał": null,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "",
	  "rozstanie": "",
	  "czy_szukają": "",
	  "seks_bez_zob": "",
	  "partnerka_z_uni": "",
	  "konto_randkowe": "tak",
	  "jak_często": "codziennie",
	  "dzowni_przed": "",
	  "dąży_do_spotkania": "",
	  "jaki_cel": "",
	  "pandemia": "tak",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "tak",
	  "sexting": "nie",
	  "seks": "nie",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "tak",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "ścisłe",
	  "płeć": "m",
	  "wiek": 21,
	  "rok_studiów": 2,
	  "kierunek": "informatyka",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 24,
	  "szukają_długoterm": "nie",
	  "krótkotrwały_zw": "tak",
	  "partner_internet": "nie",
	  "platforma": "",
	  "zw_odległość": "nie",
	  "rozstanie": "różnica wartości",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "nie",
	  "partnerka_z_uni": "tak",
	  "konto_randkowe": "tak",
	  "jak_często": "kilka razy tygodniowo",
	  "dzowni_przed": "nie",
	  "dąży_do_spotkania": "tak",
	  "jaki_cel": "partnera",
	  "pandemia": "",
	  "co_ważniejsze": "partner",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "nie",
	  "kiedyś_łatwiej": "tak",
	  "warto_szukać": "tak",
	  "nie_monogamia": "nie",
	  "małżeństwo": "tak",
	  "partner_ka_na_stałe": "tak",
	  "płacenie_randka": "nie",
	  "ankieta_internetowa": "nie"
   },
	{
	  "studia": "humanistyczne",
	  "płeć": "k",
	  "wiek": 22,
	  "rok_studiów": 3,
	  "kierunek": "psychologia",
	  "związek_teraz": "nie",
	  "jak_się_poznali": [
		 "",
		 "na żywo"
	  ],
	  "ile_trwa": null,
	  "na_odległość": "",
	  "czy_byli_kiedyś": "tak",
	  "ile_trwał": 6,
	  "szukają_długoterm": "",
	  "krótkotrwały_zw": "nie",
	  "partner_internet": "",
	  "platforma": "",
	  "zw_odległość": "nie",
	  "rozstanie": "niekompatybilność",
	  "czy_szukają": "nie",
	  "seks_bez_zob": "tak",
	  "partnerka_z_uni": "nie",
	  "konto_randkowe": "tak",
	  "jak_często": "kilka razy tygodniowo",
	  "dzowni_przed": "nie",
	  "dąży_do_spotkania": "tak",
	  "jaki_cel": "partnera",
	  "pandemia": "nie",
	  "co_ważniejsze": "nauka/praca",
	  "presja_równa_się_krótko": "nie",
	  "sexting": "tak",
	  "seks": "tak",
	  "ta_sama_płeć": "tak",
	  "kiedyś_łatwiej": "nie",
	  "warto_szukać": "nie",
	  "nie_monogamia": "nie",
	  "małżeństwo": "nie",
	  "partner_ka_na_stałe": "nie",
	  "płacenie_randka": "tak",
	  "ankieta_internetowa": "nie"
   }
]